# Generated by Django 3.0.8 on 2020-10-12 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('passport', models.CharField(max_length=40, unique=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('result', models.BooleanField(default=False)),
            ],
        ),
    ]
