# Generated by Django 3.0.8 on 2020-10-15 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='result',
        ),
        migrations.AddField(
            model_name='exam',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
