# Generated by Django 3.0.8 on 2020-10-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0005_auto_20201027_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='result',
            field=models.CharField(choices=[(1, 'None'), (2, 'Negative'), (3, 'Positive')], max_length=60),
        ),
    ]
